spring.datasource.url=jdbc:postgresql://auth-postgres:5432/auth_service
spring.datasource.username=crowns
spring.datasource.password=crowns
spring.jpa.hibernate.ddl-auto=create

spring.docker.compose.enabled=false
