package at.fhv.backend.domain.model.exception;

public enum ErrorCode {
    SHIP_NOT_AVAILABLE_FOR_PURCHASE,
    SHIP_INVALID_STATUS_TRANSITION,

    // Player
    PLAYER_NOT_FOUND,
    FACTION_ALREADY_ASSIGNED,
    INVALID_FACTION,
    PLAYER_INSUFFICIENT_FUNDS,
    TRAVEL_SAME_PORT,
    TRAVEL_INVALID_DATA,
    TRAVEL_INVALID_STATE,
    INSUFFICIENT_FUEL,
    SHIP_NOT_OWNED_BY_PLAYER,
    SHIP_NOT_FOUND,
    TRAVEL_NOT_FOUND,
    INVALID_AMOUNT,

    // Session
    SESSION_NOT_FOUND,
    SESSION_FULL,
    SESSION_NOT_IN_LOBBY,
    SESSION_NOT_RUNNING,
    ONLY_HOST_CAN_START,
    INVALID_TICK_RATE,
    PLAYER_ALREADY_IN_SESSION,

    // Cargo
    CARGO_NOT_AVAILABLE,
    CARGO_NOT_ASSIGNED,
    CARGO_NOT_FOUND,
    CARGO_CAPACITY_EXCEEDED,
    CUSTOMS_INSPECTION_NOT_FOUND,
    CUSTOMS_INSPECTION_INVALID_STATE,

    SMUGGLE_EXPIRED,
    SMUGGLE_NOT_FOUND,

    PILOT_STRIKE_ACTIVE,

    // Home Port
    HOME_PORT_NOT_ASSIGNED,
    HOME_PORT_ALREADY_ASSIGNED


}
