package at.fhv.backend.domain.model.exception;

public enum ErrorCode {
    SHIP_NOT_AVAILABLE_FOR_PURCHASE,
    SHIP_INVALID_STATUS_TRANSITION,
    PLAYER_INSUFFICIENT_FUNDS,
    TRAVEL_SAME_PORT,
    TRAVEL_INVALID_DATA,
    TRAVEL_INVALID_STATE,
    INSUFFICIENT_FUEL,
    SHIP_NOT_OWNED_BY_PLAYER,
    SHIP_NOT_FOUND,
    TRAVEL_NOT_FOUND
}
