package at.fhv.backend.domain.model.exception;

public enum ErrorCode {
    SHIP_NOT_AVAILABLE_FOR_PURCHASE,
    SHIP_INVALID_STATUS_TRANSITION,
    // User
    USERNAME_ALREADY_EXISTS,
    INVALID_CREDENTIALS,

    // Player
    PLAYER_NOT_FOUND,
    FACTION_ALREADY_ASSIGNED,
    INVALID_FACTION,
    PLAYER_INSUFFICIENT_FUNDS,
    TRAVEL_SAME_PORT,
    TRAVEL_INVALID_DATA,
    TRAVEL_INVALID_STATE,
    INSUFFICIENT_FUEL,
    SHIP_NOT_OWNED_BY_PLAYER,
    SHIP_NOT_FOUND,
    TRAVEL_NOT_FOUND,
    INVALID_AMOUNT,

    // Session
    SESSION_NOT_FOUND,
    SESSION_FULL,
    SESSION_NOT_IN_LOBBY,
    SESSION_NOT_RUNNING,
    ONLY_HOST_CAN_START,
    INVALID_TICK_RATE
}
