spring.datasource.url=jdbc:postgresql://ep-patient-credit-a92e0hmu-pooler.gwc.azure.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_utgAJnql2N6X

spring.docker.compose.enabled=false
