spring.datasource.url=jdbc:postgresql://localhost:5432/crowns_of_the_seas
spring.datasource.username=crowns
spring.datasource.password=crowns

spring.docker.compose.file=../docker-compose.yml
spring.docker.compose.profiles.active=local
