spring.datasource.url=jdbc:postgresql://postgres:5432/crowns_of_the_seas
spring.datasource.username=crowns
spring.datasource.password=crowns
spring.jpa.hibernate.ddl-auto=update

spring.docker.compose.enabled=false
